#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("size", 32, hls_in, 0, "ap_stable", "in_data", 1),
	Port_Property("dim", 32, hls_in, 1, "ap_stable", "in_data", 1),
	Port_Property("threshold_V", 34, hls_in, 2, "ap_stable", "in_data", 1),
	Port_Property("data0_0_V", 17, hls_in, 3, "ap_stable", "in_data", 1),
	Port_Property("data0_1_V", 17, hls_in, 4, "ap_stable", "in_data", 1),
	Port_Property("data0_2_V", 17, hls_in, 5, "ap_stable", "in_data", 1),
	Port_Property("data0_3_V", 17, hls_in, 6, "ap_stable", "in_data", 1),
	Port_Property("data0_4_V", 17, hls_in, 7, "ap_stable", "in_data", 1),
	Port_Property("data0_5_V", 17, hls_in, 8, "ap_stable", "in_data", 1),
	Port_Property("data0_6_V", 17, hls_in, 9, "ap_stable", "in_data", 1),
	Port_Property("data0_7_V", 17, hls_in, 10, "ap_stable", "in_data", 1),
	Port_Property("data0_8_V", 17, hls_in, 11, "ap_stable", "in_data", 1),
	Port_Property("data0_9_V", 17, hls_in, 12, "ap_stable", "in_data", 1),
	Port_Property("data0_10_V", 17, hls_in, 13, "ap_stable", "in_data", 1),
	Port_Property("data0_11_V", 17, hls_in, 14, "ap_stable", "in_data", 1),
	Port_Property("data0_12_V", 17, hls_in, 15, "ap_stable", "in_data", 1),
	Port_Property("data0_13_V", 17, hls_in, 16, "ap_stable", "in_data", 1),
	Port_Property("data0_14_V", 17, hls_in, 17, "ap_stable", "in_data", 1),
	Port_Property("data0_15_V", 17, hls_in, 18, "ap_stable", "in_data", 1),
	Port_Property("my_input1_V_TDATA", 24, hls_in, 19, "axis", "in_data", 1),
	Port_Property("my_input1_V_TVALID", 1, hls_in, 19, "axis", "in_vld", 1),
	Port_Property("my_input1_V_TREADY", 1, hls_out, 19, "axis", "in_acc", 1),
	Port_Property("my_output_V_TDATA", 40, hls_out, 20, "axis", "out_data", 1),
	Port_Property("my_output_V_TVALID", 1, hls_out, 20, "axis", "out_vld", 1),
	Port_Property("my_output_V_TREADY", 1, hls_in, 20, "axis", "out_acc", 1),
};
const char* HLS_Design_Meta::dut_name = "myFuncAccel4";
