// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="myFuncAccel4,hls_ip_2019_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.974200,HLS_SYN_LAT=431,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=20,HLS_SYN_FF=3761,HLS_SYN_LUT=4461,HLS_VERSION=2019_1}" *)

module myFuncAccel4 (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        size,
        dim,
        threshold,
        data0_0,
        data0_1,
        data0_2,
        data0_3,
        data0_4,
        data0_5,
        data0_6,
        data0_7,
        data0_8,
        data0_9,
        data0_10,
        data0_11,
        data0_12,
        data0_13,
        data0_14,
        data0_15,
        my_input1_TDATA,
        my_input1_TVALID,
        my_input1_TREADY,
        my_output_TDATA,
        my_output_TVALID,
        my_output_TREADY
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_pp0_stage0 = 6'd2;
parameter    ap_ST_fsm_pp0_stage1 = 6'd4;
parameter    ap_ST_fsm_pp0_stage2 = 6'd8;
parameter    ap_ST_fsm_pp0_stage3 = 6'd16;
parameter    ap_ST_fsm_state36 = 6'd32;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] size;
input  [31:0] dim;
input  [31:0] threshold;
input  [31:0] data0_0;
input  [31:0] data0_1;
input  [31:0] data0_2;
input  [31:0] data0_3;
input  [31:0] data0_4;
input  [31:0] data0_5;
input  [31:0] data0_6;
input  [31:0] data0_7;
input  [31:0] data0_8;
input  [31:0] data0_9;
input  [31:0] data0_10;
input  [31:0] data0_11;
input  [31:0] data0_12;
input  [31:0] data0_13;
input  [31:0] data0_14;
input  [31:0] data0_15;
input  [31:0] my_input1_TDATA;
input   my_input1_TVALID;
output   my_input1_TREADY;
output  [31:0] my_output_TDATA;
output   my_output_TVALID;
input   my_output_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] my_input1_0_data_out;
wire    my_input1_0_vld_in;
wire    my_input1_0_vld_out;
wire    my_input1_0_ack_in;
reg    my_input1_0_ack_out;
reg   [31:0] my_input1_0_payload_A;
reg   [31:0] my_input1_0_payload_B;
reg    my_input1_0_sel_rd;
reg    my_input1_0_sel_wr;
wire    my_input1_0_sel;
wire    my_input1_0_load_A;
wire    my_input1_0_load_B;
reg   [1:0] my_input1_0_state;
wire    my_input1_0_state_cmp_full;
reg   [31:0] my_output_1_data_in;
reg   [31:0] my_output_1_data_out;
reg    my_output_1_vld_in;
wire    my_output_1_vld_out;
wire    my_output_1_ack_in;
wire    my_output_1_ack_out;
reg   [31:0] my_output_1_payload_A;
reg   [31:0] my_output_1_payload_B;
reg    my_output_1_sel_rd;
reg    my_output_1_sel_wr;
wire    my_output_1_sel;
wire    my_output_1_load_A;
wire    my_output_1_load_B;
reg   [1:0] my_output_1_state;
wire    my_output_1_state_cmp_full;
reg    my_input1_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln34_fu_298_p2;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1;
reg   [0:0] icmp_ln34_reg_685;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3;
reg    my_output_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter7;
reg   [0:0] icmp_ln34_reg_685_pp0_iter7_reg;
reg    ap_enable_reg_pp0_iter8;
reg   [0:0] icmp_ln34_reg_685_pp0_iter8_reg;
reg   [31:0] i_1_reg_229;
wire   [31:0] bitcast_ln53_1_fu_284_p1;
wire   [0:0] icmp_ln53_3_fu_292_p2;
reg    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state6_pp0_stage0_iter1;
wire    ap_block_state10_pp0_stage0_iter2;
wire    ap_block_state14_pp0_stage0_iter3;
wire    ap_block_state18_pp0_stage0_iter4;
wire    ap_block_state22_pp0_stage0_iter5;
wire    ap_block_state26_pp0_stage0_iter6;
wire    ap_block_state30_pp0_stage0_iter7;
wire    ap_block_state34_pp0_stage0_iter8;
reg    ap_block_state34_io;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln34_reg_685_pp0_iter1_reg;
reg   [0:0] icmp_ln34_reg_685_pp0_iter2_reg;
reg   [0:0] icmp_ln34_reg_685_pp0_iter3_reg;
reg   [0:0] icmp_ln34_reg_685_pp0_iter4_reg;
reg   [0:0] icmp_ln34_reg_685_pp0_iter5_reg;
reg   [0:0] icmp_ln34_reg_685_pp0_iter6_reg;
wire   [31:0] i_fu_303_p2;
reg   [31:0] i_reg_689;
wire   [0:0] or_ln53_1_fu_324_p2;
reg    ap_block_state3_pp0_stage1_iter0;
wire    ap_block_state7_pp0_stage1_iter1;
wire    ap_block_state11_pp0_stage1_iter2;
wire    ap_block_state15_pp0_stage1_iter3;
wire    ap_block_state19_pp0_stage1_iter4;
wire    ap_block_state23_pp0_stage1_iter5;
wire    ap_block_state27_pp0_stage1_iter6;
wire    ap_block_state31_pp0_stage1_iter7;
reg    ap_block_state31_io;
wire    ap_block_state35_pp0_stage1_iter8;
reg    ap_block_state35_io;
reg    ap_block_pp0_stage1_11001;
reg    ap_block_state4_pp0_stage2_iter0;
wire    ap_block_state8_pp0_stage2_iter1;
wire    ap_block_state12_pp0_stage2_iter2;
wire    ap_block_state16_pp0_stage2_iter3;
wire    ap_block_state20_pp0_stage2_iter4;
wire    ap_block_state24_pp0_stage2_iter5;
wire    ap_block_state28_pp0_stage2_iter6;
wire    ap_block_state32_pp0_stage2_iter7;
reg    ap_block_state32_io;
reg    ap_block_pp0_stage2_11001;
reg    ap_block_state5_pp0_stage3_iter0;
wire    ap_block_state9_pp0_stage3_iter1;
wire    ap_block_state13_pp0_stage3_iter2;
wire    ap_block_state17_pp0_stage3_iter3;
wire    ap_block_state21_pp0_stage3_iter4;
wire    ap_block_state25_pp0_stage3_iter5;
wire    ap_block_state29_pp0_stage3_iter6;
wire    ap_block_state33_pp0_stage3_iter7;
reg    ap_block_state33_io;
reg    ap_block_pp0_stage3_11001;
wire   [31:0] grp_fu_260_p2;
reg   [31:0] tmp_2_reg_734;
wire   [31:0] grp_fu_265_p2;
reg   [31:0] tmp_2_1_reg_739;
wire   [31:0] grp_fu_270_p2;
reg   [31:0] tmp_2_2_reg_744;
wire   [31:0] grp_fu_275_p2;
reg   [31:0] tmp_2_3_reg_749;
reg   [31:0] tmp_2_0_1_reg_754;
reg    ap_enable_reg_pp0_iter1;
reg   [31:0] tmp_2_0_1_reg_754_pp0_iter2_reg;
reg   [31:0] tmp_2_1_1_reg_759;
reg   [31:0] tmp_2_1_1_reg_759_pp0_iter2_reg;
reg   [31:0] tmp_2_2_1_reg_764;
reg   [31:0] tmp_2_2_1_reg_764_pp0_iter2_reg;
reg   [31:0] tmp_2_3_1_reg_769;
reg   [31:0] tmp_2_3_1_reg_769_pp0_iter2_reg;
reg   [31:0] tmp_2_0_2_reg_774;
reg   [31:0] tmp_2_0_2_reg_774_pp0_iter2_reg;
reg   [31:0] tmp_2_0_2_reg_774_pp0_iter3_reg;
reg   [31:0] tmp_2_1_2_reg_779;
reg   [31:0] tmp_2_1_2_reg_779_pp0_iter2_reg;
reg   [31:0] tmp_2_1_2_reg_779_pp0_iter3_reg;
reg   [31:0] tmp_2_2_2_reg_784;
reg   [31:0] tmp_2_2_2_reg_784_pp0_iter2_reg;
reg   [31:0] tmp_2_2_2_reg_784_pp0_iter3_reg;
reg   [31:0] tmp_2_3_2_reg_789;
reg   [31:0] tmp_2_3_2_reg_789_pp0_iter2_reg;
reg   [31:0] tmp_2_3_2_reg_789_pp0_iter3_reg;
reg   [31:0] tmp_2_0_3_reg_794;
reg   [31:0] tmp_2_0_3_reg_794_pp0_iter2_reg;
reg   [31:0] tmp_2_0_3_reg_794_pp0_iter3_reg;
reg   [31:0] tmp_2_0_3_reg_794_pp0_iter4_reg;
reg   [31:0] tmp_2_1_3_reg_799;
reg   [31:0] tmp_2_1_3_reg_799_pp0_iter2_reg;
reg   [31:0] tmp_2_1_3_reg_799_pp0_iter3_reg;
reg   [31:0] tmp_2_1_3_reg_799_pp0_iter4_reg;
reg   [31:0] tmp_2_2_3_reg_804;
reg   [31:0] tmp_2_2_3_reg_804_pp0_iter2_reg;
reg   [31:0] tmp_2_2_3_reg_804_pp0_iter3_reg;
reg   [31:0] tmp_2_2_3_reg_804_pp0_iter4_reg;
reg   [31:0] tmp_2_3_3_reg_809;
reg   [31:0] tmp_2_3_3_reg_809_pp0_iter2_reg;
reg   [31:0] tmp_2_3_3_reg_809_pp0_iter3_reg;
reg   [31:0] tmp_2_3_3_reg_809_pp0_iter4_reg;
wire   [31:0] grp_fu_240_p2;
reg   [31:0] tmp_3_reg_814;
reg    ap_enable_reg_pp0_iter2;
wire   [31:0] grp_fu_245_p2;
reg   [31:0] tmp_3_1_reg_819;
wire   [31:0] grp_fu_250_p2;
reg   [31:0] tmp_3_2_reg_824;
wire   [31:0] grp_fu_255_p2;
reg   [31:0] tmp_3_3_reg_829;
reg   [31:0] tmp_3_0_1_reg_834;
reg    ap_enable_reg_pp0_iter3;
reg   [31:0] tmp_3_1_1_reg_839;
reg   [31:0] tmp_3_2_1_reg_844;
reg   [31:0] tmp_3_3_1_reg_849;
reg   [31:0] tmp_3_0_2_reg_854;
reg    ap_enable_reg_pp0_iter4;
reg   [31:0] tmp_3_1_2_reg_859;
reg   [31:0] tmp_3_2_2_reg_864;
reg   [31:0] tmp_3_3_2_reg_869;
reg   [31:0] tmp_3_0_3_reg_874;
reg    ap_enable_reg_pp0_iter5;
reg   [31:0] tmp_3_0_3_reg_874_pp0_iter6_reg;
reg   [31:0] tmp_3_1_3_reg_881;
reg   [31:0] tmp_3_1_3_reg_881_pp0_iter6_reg;
reg   [31:0] tmp_3_2_3_reg_888;
reg   [31:0] tmp_3_2_3_reg_888_pp0_iter6_reg;
reg   [31:0] tmp_3_3_3_reg_895;
reg   [31:0] tmp_3_3_3_reg_895_pp0_iter6_reg;
wire   [0:0] grp_fu_280_p2;
reg   [0:0] tmp_5_reg_902;
reg    ap_enable_reg_pp0_iter6;
reg   [0:0] tmp_8_reg_907;
reg   [0:0] tmp_s_reg_912;
wire   [1:0] add_ln53_fu_526_p2;
reg   [1:0] add_ln53_reg_917;
wire   [1:0] add_ln53_1_fu_532_p2;
reg   [1:0] add_ln53_1_reg_922;
wire   [31:0] p_tmp_3_0_3_fu_556_p3;
wire   [31:0] p_tmp_3_1_3_fu_564_p3;
reg   [31:0] p_tmp_3_1_3_reg_932;
wire   [31:0] p_tmp_3_2_3_fu_571_p3;
reg   [31:0] p_tmp_3_2_3_reg_937;
wire   [31:0] p_tmp_3_3_3_fu_578_p3;
reg   [31:0] p_tmp_3_3_3_reg_942;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_block_pp0_stage3_subdone;
reg    ap_block_pp0_stage1_subdone;
reg   [31:0] ap_phi_mux_i_1_phi_fu_233_p4;
reg    ap_block_pp0_stage1_01001;
reg    ap_block_pp0_stage2_01001;
reg    ap_block_pp0_stage3_01001;
reg    ap_block_pp0_stage0_01001;
reg   [31:0] grp_fu_240_p0;
reg   [31:0] grp_fu_240_p1;
reg   [31:0] grp_fu_245_p0;
reg   [31:0] grp_fu_245_p1;
reg   [31:0] grp_fu_250_p0;
reg   [31:0] grp_fu_250_p1;
reg   [31:0] grp_fu_255_p0;
reg   [31:0] grp_fu_255_p1;
reg   [31:0] grp_fu_260_p0;
reg   [31:0] grp_fu_265_p0;
reg   [31:0] grp_fu_270_p0;
reg   [31:0] grp_fu_275_p0;
reg   [31:0] grp_fu_280_p0;
wire   [22:0] trunc_ln53_fu_288_p1;
wire   [7:0] tmp_4_fu_309_p4;
wire   [0:0] icmp_ln53_2_fu_318_p2;
wire   [31:0] bitcast_ln53_fu_329_p1;
wire   [7:0] tmp_1_fu_332_p4;
wire   [22:0] trunc_ln53_1_fu_342_p1;
wire   [0:0] icmp_ln53_1_fu_352_p2;
wire   [0:0] icmp_ln53_fu_346_p2;
wire   [0:0] or_ln53_fu_358_p2;
wire   [0:0] and_ln53_fu_364_p2;
wire   [0:0] and_ln53_1_fu_369_p2;
wire   [31:0] bitcast_ln53_2_fu_378_p1;
wire   [7:0] tmp_6_fu_381_p4;
wire   [22:0] trunc_ln53_2_fu_391_p1;
wire   [0:0] icmp_ln53_5_fu_401_p2;
wire   [0:0] icmp_ln53_4_fu_395_p2;
wire   [0:0] or_ln53_2_fu_407_p2;
wire   [0:0] and_ln53_2_fu_413_p2;
wire   [0:0] and_ln53_3_fu_418_p2;
wire   [31:0] bitcast_ln53_3_fu_427_p1;
wire   [7:0] tmp_9_fu_430_p4;
wire   [22:0] trunc_ln53_3_fu_440_p1;
wire   [0:0] icmp_ln53_7_fu_450_p2;
wire   [0:0] icmp_ln53_6_fu_444_p2;
wire   [0:0] or_ln53_3_fu_456_p2;
wire   [0:0] and_ln53_4_fu_462_p2;
wire   [0:0] and_ln53_5_fu_467_p2;
wire   [31:0] bitcast_ln53_4_fu_476_p1;
wire   [7:0] tmp_7_fu_479_p4;
wire   [22:0] trunc_ln53_4_fu_489_p1;
wire   [0:0] icmp_ln53_9_fu_499_p2;
wire   [0:0] icmp_ln53_8_fu_493_p2;
wire   [0:0] or_ln53_4_fu_505_p2;
wire   [0:0] and_ln53_6_fu_511_p2;
wire   [0:0] and_ln53_7_fu_516_p2;
wire   [1:0] zext_ln51_1_fu_423_p1;
wire   [1:0] zext_ln51_fu_374_p1;
wire   [1:0] zext_ln51_2_fu_472_p1;
wire   [1:0] zext_ln53_fu_522_p1;
wire   [2:0] zext_ln53_2_fu_541_p1;
wire   [2:0] zext_ln53_1_fu_538_p1;
wire   [2:0] add_ln53_2_fu_544_p2;
wire   [0:0] icmp_ln55_fu_550_p2;
reg    grp_fu_240_ce;
reg    grp_fu_245_ce;
reg    grp_fu_250_ce;
reg    grp_fu_255_ce;
reg    grp_fu_260_ce;
reg    grp_fu_265_ce;
reg    grp_fu_270_ce;
reg    grp_fu_275_ce;
reg    grp_fu_280_ce;
reg    ap_block_pp0_stage0_00001;
reg    ap_block_pp0_stage1_00001;
reg    ap_block_pp0_stage2_00001;
reg    ap_block_pp0_stage3_00001;
wire    ap_CS_fsm_state36;
reg    ap_block_state36;
reg   [5:0] ap_NS_fsm;
reg    ap_block_pp0_stage2_subdone;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_629;
reg    ap_condition_634;
reg    ap_condition_639;
reg    ap_condition_644;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 my_input1_0_sel_rd = 1'b0;
#0 my_input1_0_sel_wr = 1'b0;
#0 my_input1_0_state = 2'd0;
#0 my_output_1_sel_rd = 1'b0;
#0 my_output_1_sel_wr = 1'b0;
#0 my_output_1_state = 2'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
end

myFuncAccel4_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
myFuncAccel4_fadd_32ns_32ns_32_5_full_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_240_p0),
    .din1(grp_fu_240_p1),
    .ce(grp_fu_240_ce),
    .dout(grp_fu_240_p2)
);

myFuncAccel4_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
myFuncAccel4_fadd_32ns_32ns_32_5_full_dsp_1_U2(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_245_p0),
    .din1(grp_fu_245_p1),
    .ce(grp_fu_245_ce),
    .dout(grp_fu_245_p2)
);

myFuncAccel4_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
myFuncAccel4_fadd_32ns_32ns_32_5_full_dsp_1_U3(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_250_p0),
    .din1(grp_fu_250_p1),
    .ce(grp_fu_250_ce),
    .dout(grp_fu_250_p2)
);

myFuncAccel4_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
myFuncAccel4_fadd_32ns_32ns_32_5_full_dsp_1_U4(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_255_p0),
    .din1(grp_fu_255_p1),
    .ce(grp_fu_255_ce),
    .dout(grp_fu_255_p2)
);

myFuncAccel4_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
myFuncAccel4_fmul_32ns_32ns_32_4_max_dsp_1_U5(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_260_p0),
    .din1(my_input1_0_data_out),
    .ce(grp_fu_260_ce),
    .dout(grp_fu_260_p2)
);

myFuncAccel4_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
myFuncAccel4_fmul_32ns_32ns_32_4_max_dsp_1_U6(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_265_p0),
    .din1(my_input1_0_data_out),
    .ce(grp_fu_265_ce),
    .dout(grp_fu_265_p2)
);

myFuncAccel4_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
myFuncAccel4_fmul_32ns_32ns_32_4_max_dsp_1_U7(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_270_p0),
    .din1(my_input1_0_data_out),
    .ce(grp_fu_270_ce),
    .dout(grp_fu_270_p2)
);

myFuncAccel4_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
myFuncAccel4_fmul_32ns_32ns_32_4_max_dsp_1_U8(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_275_p0),
    .din1(my_input1_0_data_out),
    .ce(grp_fu_275_ce),
    .dout(grp_fu_275_p2)
);

myFuncAccel4_fcmp_32ns_32ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
myFuncAccel4_fcmp_32ns_32ns_1_2_1_U9(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_280_p0),
    .din1(threshold),
    .ce(grp_fu_280_ce),
    .opcode(5'd2),
    .dout(grp_fu_280_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter8 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        my_input1_0_sel_rd <= 1'b0;
    end else begin
        if (((my_input1_0_ack_out == 1'b1) & (my_input1_0_vld_out == 1'b1))) begin
            my_input1_0_sel_rd <= ~my_input1_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        my_input1_0_sel_wr <= 1'b0;
    end else begin
        if (((my_input1_0_ack_in == 1'b1) & (my_input1_0_vld_in == 1'b1))) begin
            my_input1_0_sel_wr <= ~my_input1_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        my_input1_0_state <= 2'd0;
    end else begin
        if ((((my_input1_0_state == 2'd2) & (my_input1_0_vld_in == 1'b0)) | ((my_input1_0_state == 2'd3) & (my_input1_0_vld_in == 1'b0) & (my_input1_0_ack_out == 1'b1)))) begin
            my_input1_0_state <= 2'd2;
        end else if ((((my_input1_0_state == 2'd1) & (my_input1_0_ack_out == 1'b0)) | ((my_input1_0_state == 2'd3) & (my_input1_0_ack_out == 1'b0) & (my_input1_0_vld_in == 1'b1)))) begin
            my_input1_0_state <= 2'd1;
        end else if (((~((my_input1_0_vld_in == 1'b0) & (my_input1_0_ack_out == 1'b1)) & ~((my_input1_0_ack_out == 1'b0) & (my_input1_0_vld_in == 1'b1)) & (my_input1_0_state == 2'd3)) | ((my_input1_0_state == 2'd1) & (my_input1_0_ack_out == 1'b1)) | ((my_input1_0_state == 2'd2) & (my_input1_0_vld_in == 1'b1)))) begin
            my_input1_0_state <= 2'd3;
        end else begin
            my_input1_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        my_output_1_sel_rd <= 1'b0;
    end else begin
        if (((my_output_1_ack_out == 1'b1) & (my_output_1_vld_out == 1'b1))) begin
            my_output_1_sel_rd <= ~my_output_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        my_output_1_sel_wr <= 1'b0;
    end else begin
        if (((my_output_1_ack_in == 1'b1) & (my_output_1_vld_in == 1'b1))) begin
            my_output_1_sel_wr <= ~my_output_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        my_output_1_state <= 2'd0;
    end else begin
        if ((((my_output_1_state == 2'd2) & (my_output_1_vld_in == 1'b0)) | ((my_output_1_state == 2'd3) & (my_output_1_vld_in == 1'b0) & (my_output_1_ack_out == 1'b1)))) begin
            my_output_1_state <= 2'd2;
        end else if ((((my_output_1_state == 2'd1) & (my_output_TREADY == 1'b0)) | ((my_output_1_state == 2'd3) & (my_output_TREADY == 1'b0) & (my_output_1_vld_in == 1'b1)))) begin
            my_output_1_state <= 2'd1;
        end else if (((~((my_output_1_vld_in == 1'b0) & (my_output_1_ack_out == 1'b1)) & ~((my_output_TREADY == 1'b0) & (my_output_1_vld_in == 1'b1)) & (my_output_1_state == 2'd3)) | ((my_output_1_state == 2'd1) & (my_output_1_ack_out == 1'b1)) | ((my_output_1_state == 2'd2) & (my_output_1_vld_in == 1'b1)))) begin
            my_output_1_state <= 2'd3;
        end else begin
            my_output_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_1_reg_229 <= 32'd0;
    end else if (((icmp_ln34_reg_685 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_1_reg_229 <= i_reg_689;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln34_reg_685_pp0_iter6_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln53_1_reg_922 <= add_ln53_1_fu_532_p2;
        add_ln53_reg_917 <= add_ln53_fu_526_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_689 <= i_fu_303_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln34_reg_685 <= icmp_ln34_fu_298_p2;
        icmp_ln34_reg_685_pp0_iter1_reg <= icmp_ln34_reg_685;
        icmp_ln34_reg_685_pp0_iter2_reg <= icmp_ln34_reg_685_pp0_iter1_reg;
        icmp_ln34_reg_685_pp0_iter3_reg <= icmp_ln34_reg_685_pp0_iter2_reg;
        icmp_ln34_reg_685_pp0_iter4_reg <= icmp_ln34_reg_685_pp0_iter3_reg;
        icmp_ln34_reg_685_pp0_iter5_reg <= icmp_ln34_reg_685_pp0_iter4_reg;
        icmp_ln34_reg_685_pp0_iter6_reg <= icmp_ln34_reg_685_pp0_iter5_reg;
        icmp_ln34_reg_685_pp0_iter7_reg <= icmp_ln34_reg_685_pp0_iter6_reg;
        icmp_ln34_reg_685_pp0_iter8_reg <= icmp_ln34_reg_685_pp0_iter7_reg;
        tmp_2_0_1_reg_754_pp0_iter2_reg <= tmp_2_0_1_reg_754;
        tmp_2_1_1_reg_759_pp0_iter2_reg <= tmp_2_1_1_reg_759;
        tmp_2_2_1_reg_764_pp0_iter2_reg <= tmp_2_2_1_reg_764;
        tmp_2_3_1_reg_769_pp0_iter2_reg <= tmp_2_3_1_reg_769;
    end
end

always @ (posedge ap_clk) begin
    if ((my_input1_0_load_A == 1'b1)) begin
        my_input1_0_payload_A <= my_input1_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((my_input1_0_load_B == 1'b1)) begin
        my_input1_0_payload_B <= my_input1_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((my_output_1_load_A == 1'b1)) begin
        my_output_1_payload_A <= my_output_1_data_in;
    end
end

always @ (posedge ap_clk) begin
    if ((my_output_1_load_B == 1'b1)) begin
        my_output_1_payload_B <= my_output_1_data_in;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln34_reg_685_pp0_iter7_reg == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_tmp_3_1_3_reg_932 <= p_tmp_3_1_3_fu_564_p3;
        p_tmp_3_2_3_reg_937 <= p_tmp_3_2_3_fu_571_p3;
        p_tmp_3_3_3_reg_942 <= p_tmp_3_3_3_fu_578_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln34_reg_685 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_2_0_1_reg_754 <= grp_fu_260_p2;
        tmp_2_1_1_reg_759 <= grp_fu_265_p2;
        tmp_2_2_1_reg_764 <= grp_fu_270_p2;
        tmp_2_3_1_reg_769 <= grp_fu_275_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln34_reg_685_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_2_0_2_reg_774 <= grp_fu_260_p2;
        tmp_2_1_2_reg_779 <= grp_fu_265_p2;
        tmp_2_2_2_reg_784 <= grp_fu_270_p2;
        tmp_2_3_2_reg_789 <= grp_fu_275_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_2_0_2_reg_774_pp0_iter2_reg <= tmp_2_0_2_reg_774;
        tmp_2_0_2_reg_774_pp0_iter3_reg <= tmp_2_0_2_reg_774_pp0_iter2_reg;
        tmp_2_1_2_reg_779_pp0_iter2_reg <= tmp_2_1_2_reg_779;
        tmp_2_1_2_reg_779_pp0_iter3_reg <= tmp_2_1_2_reg_779_pp0_iter2_reg;
        tmp_2_2_2_reg_784_pp0_iter2_reg <= tmp_2_2_2_reg_784;
        tmp_2_2_2_reg_784_pp0_iter3_reg <= tmp_2_2_2_reg_784_pp0_iter2_reg;
        tmp_2_3_2_reg_789_pp0_iter2_reg <= tmp_2_3_2_reg_789;
        tmp_2_3_2_reg_789_pp0_iter3_reg <= tmp_2_3_2_reg_789_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln34_reg_685_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        tmp_2_0_3_reg_794 <= grp_fu_260_p2;
        tmp_2_1_3_reg_799 <= grp_fu_265_p2;
        tmp_2_2_3_reg_804 <= grp_fu_270_p2;
        tmp_2_3_3_reg_809 <= grp_fu_275_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        tmp_2_0_3_reg_794_pp0_iter2_reg <= tmp_2_0_3_reg_794;
        tmp_2_0_3_reg_794_pp0_iter3_reg <= tmp_2_0_3_reg_794_pp0_iter2_reg;
        tmp_2_0_3_reg_794_pp0_iter4_reg <= tmp_2_0_3_reg_794_pp0_iter3_reg;
        tmp_2_1_3_reg_799_pp0_iter2_reg <= tmp_2_1_3_reg_799;
        tmp_2_1_3_reg_799_pp0_iter3_reg <= tmp_2_1_3_reg_799_pp0_iter2_reg;
        tmp_2_1_3_reg_799_pp0_iter4_reg <= tmp_2_1_3_reg_799_pp0_iter3_reg;
        tmp_2_2_3_reg_804_pp0_iter2_reg <= tmp_2_2_3_reg_804;
        tmp_2_2_3_reg_804_pp0_iter3_reg <= tmp_2_2_3_reg_804_pp0_iter2_reg;
        tmp_2_2_3_reg_804_pp0_iter4_reg <= tmp_2_2_3_reg_804_pp0_iter3_reg;
        tmp_2_3_3_reg_809_pp0_iter2_reg <= tmp_2_3_3_reg_809;
        tmp_2_3_3_reg_809_pp0_iter3_reg <= tmp_2_3_3_reg_809_pp0_iter2_reg;
        tmp_2_3_3_reg_809_pp0_iter4_reg <= tmp_2_3_3_reg_809_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln34_reg_685 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        tmp_2_1_reg_739 <= grp_fu_265_p2;
        tmp_2_2_reg_744 <= grp_fu_270_p2;
        tmp_2_3_reg_749 <= grp_fu_275_p2;
        tmp_2_reg_734 <= grp_fu_260_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln34_reg_685_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_3_0_1_reg_834 <= grp_fu_240_p2;
        tmp_3_1_1_reg_839 <= grp_fu_245_p2;
        tmp_3_2_1_reg_844 <= grp_fu_250_p2;
        tmp_3_3_1_reg_849 <= grp_fu_255_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln34_reg_685_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        tmp_3_0_2_reg_854 <= grp_fu_240_p2;
        tmp_3_1_2_reg_859 <= grp_fu_245_p2;
        tmp_3_2_2_reg_864 <= grp_fu_250_p2;
        tmp_3_3_2_reg_869 <= grp_fu_255_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln34_reg_685_pp0_iter5_reg == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        tmp_3_0_3_reg_874 <= grp_fu_240_p2;
        tmp_3_1_3_reg_881 <= grp_fu_245_p2;
        tmp_3_2_3_reg_888 <= grp_fu_250_p2;
        tmp_3_3_3_reg_895 <= grp_fu_255_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        tmp_3_0_3_reg_874_pp0_iter6_reg <= tmp_3_0_3_reg_874;
        tmp_3_1_3_reg_881_pp0_iter6_reg <= tmp_3_1_3_reg_881;
        tmp_3_2_3_reg_888_pp0_iter6_reg <= tmp_3_2_3_reg_888;
        tmp_3_3_3_reg_895_pp0_iter6_reg <= tmp_3_3_3_reg_895;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln34_reg_685_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_3_1_reg_819 <= grp_fu_245_p2;
        tmp_3_2_reg_824 <= grp_fu_250_p2;
        tmp_3_3_reg_829 <= grp_fu_255_p2;
        tmp_3_reg_814 <= grp_fu_240_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln34_reg_685_pp0_iter6_reg == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_5_reg_902 <= grp_fu_280_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln34_reg_685_pp0_iter6_reg == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        tmp_8_reg_907 <= grp_fu_280_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln34_reg_685_pp0_iter6_reg == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        tmp_s_reg_912 <= grp_fu_280_p2;
    end
end

always @ (*) begin
    if ((icmp_ln34_fu_298_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((~((my_output_1_state == 2'd1) | ((my_output_1_state == 2'd3) & (my_output_TREADY == 1'b0))) & (1'b1 == ap_CS_fsm_state36))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_reg_685 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_i_1_phi_fu_233_p4 = i_reg_689;
    end else begin
        ap_phi_mux_i_1_phi_fu_233_p4 = i_1_reg_229;
    end
end

always @ (*) begin
    if ((~((my_output_1_state == 2'd1) | ((my_output_1_state == 2'd3) & (my_output_TREADY == 1'b0))) & (1'b1 == ap_CS_fsm_state36))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_240_ce = 1'b1;
    end else begin
        grp_fu_240_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_240_p0 = tmp_3_0_2_reg_854;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_240_p0 = tmp_3_0_1_reg_834;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        grp_fu_240_p0 = tmp_3_reg_814;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        grp_fu_240_p0 = tmp_2_reg_734;
    end else begin
        grp_fu_240_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_240_p1 = tmp_2_0_3_reg_794_pp0_iter4_reg;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_240_p1 = tmp_2_0_2_reg_774_pp0_iter3_reg;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        grp_fu_240_p1 = tmp_2_0_1_reg_754_pp0_iter2_reg;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        grp_fu_240_p1 = 32'd0;
    end else begin
        grp_fu_240_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_245_ce = 1'b1;
    end else begin
        grp_fu_245_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_245_p0 = tmp_3_1_2_reg_859;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_245_p0 = tmp_3_1_1_reg_839;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        grp_fu_245_p0 = tmp_3_1_reg_819;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        grp_fu_245_p0 = tmp_2_1_reg_739;
    end else begin
        grp_fu_245_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_245_p1 = tmp_2_1_3_reg_799_pp0_iter4_reg;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_245_p1 = tmp_2_1_2_reg_779_pp0_iter3_reg;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        grp_fu_245_p1 = tmp_2_1_1_reg_759_pp0_iter2_reg;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        grp_fu_245_p1 = 32'd0;
    end else begin
        grp_fu_245_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_250_ce = 1'b1;
    end else begin
        grp_fu_250_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_250_p0 = tmp_3_2_2_reg_864;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_250_p0 = tmp_3_2_1_reg_844;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        grp_fu_250_p0 = tmp_3_2_reg_824;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        grp_fu_250_p0 = tmp_2_2_reg_744;
    end else begin
        grp_fu_250_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_250_p1 = tmp_2_2_3_reg_804_pp0_iter4_reg;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_250_p1 = tmp_2_2_2_reg_784_pp0_iter3_reg;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        grp_fu_250_p1 = tmp_2_2_1_reg_764_pp0_iter2_reg;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        grp_fu_250_p1 = 32'd0;
    end else begin
        grp_fu_250_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_255_ce = 1'b1;
    end else begin
        grp_fu_255_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_255_p0 = tmp_3_3_2_reg_869;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_255_p0 = tmp_3_3_1_reg_849;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        grp_fu_255_p0 = tmp_3_3_reg_829;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        grp_fu_255_p0 = tmp_2_3_reg_749;
    end else begin
        grp_fu_255_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_255_p1 = tmp_2_3_3_reg_809_pp0_iter4_reg;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_255_p1 = tmp_2_3_2_reg_789_pp0_iter3_reg;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        grp_fu_255_p1 = tmp_2_3_1_reg_769_pp0_iter2_reg;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        grp_fu_255_p1 = 32'd0;
    end else begin
        grp_fu_255_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_260_ce = 1'b1;
    end else begin
        grp_fu_260_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_260_p0 = data0_3;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_260_p0 = data0_2;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
            grp_fu_260_p0 = data0_1;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
            grp_fu_260_p0 = data0_0;
        end else begin
            grp_fu_260_p0 = 'bx;
        end
    end else begin
        grp_fu_260_p0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_265_ce = 1'b1;
    end else begin
        grp_fu_265_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_265_p0 = data0_7;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_265_p0 = data0_6;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
            grp_fu_265_p0 = data0_5;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
            grp_fu_265_p0 = data0_4;
        end else begin
            grp_fu_265_p0 = 'bx;
        end
    end else begin
        grp_fu_265_p0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_270_ce = 1'b1;
    end else begin
        grp_fu_270_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_270_p0 = data0_11;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_270_p0 = data0_10;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
            grp_fu_270_p0 = data0_9;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
            grp_fu_270_p0 = data0_8;
        end else begin
            grp_fu_270_p0 = 'bx;
        end
    end else begin
        grp_fu_270_p0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_275_ce = 1'b1;
    end else begin
        grp_fu_275_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_275_p0 = data0_15;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_275_p0 = data0_14;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
            grp_fu_275_p0 = data0_13;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
            grp_fu_275_p0 = data0_12;
        end else begin
            grp_fu_275_p0 = 'bx;
        end
    end else begin
        grp_fu_275_p0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_280_ce = 1'b1;
    end else begin
        grp_fu_280_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_280_p0 = tmp_3_3_3_reg_895;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_280_p0 = tmp_3_2_3_reg_888;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
            grp_fu_280_p0 = tmp_3_1_3_reg_881;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
            grp_fu_280_p0 = tmp_3_0_3_reg_874;
        end else begin
            grp_fu_280_p0 = 'bx;
        end
    end else begin
        grp_fu_280_p0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln34_reg_685 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((icmp_ln34_reg_685 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((icmp_ln34_reg_685 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((icmp_ln34_fu_298_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        my_input1_0_ack_out = 1'b1;
    end else begin
        my_input1_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((my_input1_0_sel == 1'b1)) begin
        my_input1_0_data_out = my_input1_0_payload_B;
    end else begin
        my_input1_0_data_out = my_input1_0_payload_A;
    end
end

always @ (*) begin
    if ((((icmp_ln34_reg_685 == 1'd0) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((icmp_ln34_reg_685 == 1'd0) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((icmp_ln34_reg_685 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage1)) | ((icmp_ln34_fu_298_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)))) begin
        my_input1_TDATA_blk_n = my_input1_0_state[1'd0];
    end else begin
        my_input1_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((icmp_ln34_reg_685_pp0_iter7_reg == 1'd0)) begin
        if ((1'b1 == ap_condition_644)) begin
            my_output_1_data_in = p_tmp_3_3_3_reg_942;
        end else if ((1'b1 == ap_condition_639)) begin
            my_output_1_data_in = p_tmp_3_2_3_reg_937;
        end else if ((1'b1 == ap_condition_634)) begin
            my_output_1_data_in = p_tmp_3_1_3_reg_932;
        end else if ((1'b1 == ap_condition_629)) begin
            my_output_1_data_in = p_tmp_3_0_3_fu_556_p3;
        end else begin
            my_output_1_data_in = 'bx;
        end
    end else begin
        my_output_1_data_in = 'bx;
    end
end

always @ (*) begin
    if ((my_output_1_sel == 1'b1)) begin
        my_output_1_data_out = my_output_1_payload_B;
    end else begin
        my_output_1_data_out = my_output_1_payload_A;
    end
end

always @ (*) begin
    if ((((icmp_ln34_reg_685_pp0_iter7_reg == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((icmp_ln34_reg_685_pp0_iter7_reg == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((icmp_ln34_reg_685_pp0_iter7_reg == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((icmp_ln34_reg_685_pp0_iter7_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        my_output_1_vld_in = 1'b1;
    end else begin
        my_output_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln34_reg_685_pp0_iter7_reg == 1'd0) & (1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((icmp_ln34_reg_685_pp0_iter7_reg == 1'd0) & (1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((icmp_ln34_reg_685_pp0_iter8_reg == 1'd0) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((icmp_ln34_reg_685_pp0_iter7_reg == 1'd0) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((icmp_ln34_reg_685_pp0_iter7_reg == 1'd0) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)))) begin
        my_output_TDATA_blk_n = my_output_1_state[1'd1];
    end else begin
        my_output_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln34_fu_298_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((icmp_ln34_fu_298_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state36;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((~((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
                ap_NS_fsm = ap_ST_fsm_state36;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_state36 : begin
            if ((~((my_output_1_state == 2'd1) | ((my_output_1_state == 2'd3) & (my_output_TREADY == 1'b0))) & (1'b1 == ap_CS_fsm_state36))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state36;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln53_1_fu_532_p2 = (zext_ln51_2_fu_472_p1 + zext_ln53_fu_522_p1);

assign add_ln53_2_fu_544_p2 = (zext_ln53_2_fu_541_p1 + zext_ln53_1_fu_538_p1);

assign add_ln53_fu_526_p2 = (zext_ln51_1_fu_423_p1 + zext_ln51_fu_374_p1);

assign and_ln53_1_fu_369_p2 = (tmp_5_reg_902 & and_ln53_fu_364_p2);

assign and_ln53_2_fu_413_p2 = (or_ln53_2_fu_407_p2 & or_ln53_1_fu_324_p2);

assign and_ln53_3_fu_418_p2 = (tmp_8_reg_907 & and_ln53_2_fu_413_p2);

assign and_ln53_4_fu_462_p2 = (or_ln53_3_fu_456_p2 & or_ln53_1_fu_324_p2);

assign and_ln53_5_fu_467_p2 = (tmp_s_reg_912 & and_ln53_4_fu_462_p2);

assign and_ln53_6_fu_511_p2 = (or_ln53_4_fu_505_p2 & or_ln53_1_fu_324_p2);

assign and_ln53_7_fu_516_p2 = (grp_fu_280_p2 & and_ln53_6_fu_511_p2);

assign and_ln53_fu_364_p2 = (or_ln53_fu_358_p2 & or_ln53_1_fu_324_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_00001 = ((icmp_ln34_fu_298_p2 == 1'd0) & (my_input1_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((icmp_ln34_fu_298_p2 == 1'd0) & (my_input1_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((1'b1 == ap_block_state34_io) & (ap_enable_reg_pp0_iter8 == 1'b1)) | ((icmp_ln34_fu_298_p2 == 1'd0) & (my_input1_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((1'b1 == ap_block_state34_io) & (ap_enable_reg_pp0_iter8 == 1'b1)) | ((icmp_ln34_fu_298_p2 == 1'd0) & (my_input1_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_00001 = ((icmp_ln34_reg_685 == 1'd0) & (my_input1_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage1_01001 = ((icmp_ln34_reg_685 == 1'd0) & (my_input1_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((1'b1 == ap_block_state35_io) & (ap_enable_reg_pp0_iter8 == 1'b1)) | ((1'b1 == ap_block_state31_io) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((icmp_ln34_reg_685 == 1'd0) & (my_input1_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((1'b1 == ap_block_state35_io) & (ap_enable_reg_pp0_iter8 == 1'b1)) | ((1'b1 == ap_block_state31_io) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((icmp_ln34_reg_685 == 1'd0) & (my_input1_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_00001 = ((icmp_ln34_reg_685 == 1'd0) & (my_input1_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage2_01001 = ((icmp_ln34_reg_685 == 1'd0) & (my_input1_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage2_11001 = (((1'b1 == ap_block_state32_io) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((icmp_ln34_reg_685 == 1'd0) & (my_input1_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = (((1'b1 == ap_block_state32_io) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((icmp_ln34_reg_685 == 1'd0) & (my_input1_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_00001 = ((icmp_ln34_reg_685 == 1'd0) & (my_input1_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage3_01001 = ((icmp_ln34_reg_685 == 1'd0) & (my_input1_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage3_11001 = (((1'b1 == ap_block_state33_io) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((icmp_ln34_reg_685 == 1'd0) & (my_input1_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = (((1'b1 == ap_block_state33_io) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((icmp_ln34_reg_685 == 1'd0) & (my_input1_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

assign ap_block_state10_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage3_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage2_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage3_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage2_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage3_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage1_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage2_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage3_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage1_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage2_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage3_iter6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = ((icmp_ln34_fu_298_p2 == 1'd0) & (my_input1_0_vld_out == 1'b0));
end

assign ap_block_state30_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state31_io = ((icmp_ln34_reg_685_pp0_iter7_reg == 1'd0) & (my_output_1_ack_in == 1'b0));
end

assign ap_block_state31_pp0_stage1_iter7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state32_io = ((icmp_ln34_reg_685_pp0_iter7_reg == 1'd0) & (my_output_1_ack_in == 1'b0));
end

assign ap_block_state32_pp0_stage2_iter7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state33_io = ((icmp_ln34_reg_685_pp0_iter7_reg == 1'd0) & (my_output_1_ack_in == 1'b0));
end

assign ap_block_state33_pp0_stage3_iter7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state34_io = ((icmp_ln34_reg_685_pp0_iter7_reg == 1'd0) & (my_output_1_ack_in == 1'b0));
end

assign ap_block_state34_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state35_io = ((icmp_ln34_reg_685_pp0_iter8_reg == 1'd0) & (my_output_1_ack_in == 1'b0));
end

assign ap_block_state35_pp0_stage1_iter8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state36 = ((my_output_1_state == 2'd1) | ((my_output_1_state == 2'd3) & (my_output_TREADY == 1'b0)));
end

always @ (*) begin
    ap_block_state3_pp0_stage1_iter0 = ((icmp_ln34_reg_685 == 1'd0) & (my_input1_0_vld_out == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage2_iter0 = ((icmp_ln34_reg_685 == 1'd0) & (my_input1_0_vld_out == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage3_iter0 = ((icmp_ln34_reg_685 == 1'd0) & (my_input1_0_vld_out == 1'b0));
end

assign ap_block_state6_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_629 = ((1'b0 == ap_block_pp0_stage1_01001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

always @ (*) begin
    ap_condition_634 = ((1'b0 == ap_block_pp0_stage2_01001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2));
end

always @ (*) begin
    ap_condition_639 = ((1'b0 == ap_block_pp0_stage3_01001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3));
end

always @ (*) begin
    ap_condition_644 = ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bitcast_ln53_1_fu_284_p1 = threshold;

assign bitcast_ln53_2_fu_378_p1 = tmp_3_1_3_reg_881_pp0_iter6_reg;

assign bitcast_ln53_3_fu_427_p1 = tmp_3_2_3_reg_888_pp0_iter6_reg;

assign bitcast_ln53_4_fu_476_p1 = tmp_3_3_3_reg_895_pp0_iter6_reg;

assign bitcast_ln53_fu_329_p1 = tmp_3_0_3_reg_874_pp0_iter6_reg;

assign i_fu_303_p2 = (ap_phi_mux_i_1_phi_fu_233_p4 + 32'd1);

assign icmp_ln34_fu_298_p2 = ((ap_phi_mux_i_1_phi_fu_233_p4 == size) ? 1'b1 : 1'b0);

assign icmp_ln53_1_fu_352_p2 = ((trunc_ln53_1_fu_342_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln53_2_fu_318_p2 = ((tmp_4_fu_309_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln53_3_fu_292_p2 = ((trunc_ln53_fu_288_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln53_4_fu_395_p2 = ((tmp_6_fu_381_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln53_5_fu_401_p2 = ((trunc_ln53_2_fu_391_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln53_6_fu_444_p2 = ((tmp_9_fu_430_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln53_7_fu_450_p2 = ((trunc_ln53_3_fu_440_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln53_8_fu_493_p2 = ((tmp_7_fu_479_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln53_9_fu_499_p2 = ((trunc_ln53_4_fu_489_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln53_fu_346_p2 = ((tmp_1_fu_332_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_550_p2 = ((add_ln53_2_fu_544_p2 == 3'd4) ? 1'b1 : 1'b0);

assign my_input1_0_ack_in = my_input1_0_state[1'd1];

assign my_input1_0_load_A = (my_input1_0_state_cmp_full & ~my_input1_0_sel_wr);

assign my_input1_0_load_B = (my_input1_0_state_cmp_full & my_input1_0_sel_wr);

assign my_input1_0_sel = my_input1_0_sel_rd;

assign my_input1_0_state_cmp_full = ((my_input1_0_state != 2'd1) ? 1'b1 : 1'b0);

assign my_input1_0_vld_in = my_input1_TVALID;

assign my_input1_0_vld_out = my_input1_0_state[1'd0];

assign my_input1_TREADY = my_input1_0_state[1'd1];

assign my_output_1_ack_in = my_output_1_state[1'd1];

assign my_output_1_ack_out = my_output_TREADY;

assign my_output_1_load_A = (my_output_1_state_cmp_full & ~my_output_1_sel_wr);

assign my_output_1_load_B = (my_output_1_state_cmp_full & my_output_1_sel_wr);

assign my_output_1_sel = my_output_1_sel_rd;

assign my_output_1_state_cmp_full = ((my_output_1_state != 2'd1) ? 1'b1 : 1'b0);

assign my_output_1_vld_out = my_output_1_state[1'd0];

assign my_output_TDATA = my_output_1_data_out;

assign my_output_TVALID = my_output_1_state[1'd0];

assign or_ln53_1_fu_324_p2 = (icmp_ln53_3_fu_292_p2 | icmp_ln53_2_fu_318_p2);

assign or_ln53_2_fu_407_p2 = (icmp_ln53_5_fu_401_p2 | icmp_ln53_4_fu_395_p2);

assign or_ln53_3_fu_456_p2 = (icmp_ln53_7_fu_450_p2 | icmp_ln53_6_fu_444_p2);

assign or_ln53_4_fu_505_p2 = (icmp_ln53_9_fu_499_p2 | icmp_ln53_8_fu_493_p2);

assign or_ln53_fu_358_p2 = (icmp_ln53_fu_346_p2 | icmp_ln53_1_fu_352_p2);

assign p_tmp_3_0_3_fu_556_p3 = ((icmp_ln55_fu_550_p2[0:0] === 1'b1) ? 32'd0 : tmp_3_0_3_reg_874_pp0_iter6_reg);

assign p_tmp_3_1_3_fu_564_p3 = ((icmp_ln55_fu_550_p2[0:0] === 1'b1) ? 32'd0 : tmp_3_1_3_reg_881_pp0_iter6_reg);

assign p_tmp_3_2_3_fu_571_p3 = ((icmp_ln55_fu_550_p2[0:0] === 1'b1) ? 32'd0 : tmp_3_2_3_reg_888_pp0_iter6_reg);

assign p_tmp_3_3_3_fu_578_p3 = ((icmp_ln55_fu_550_p2[0:0] === 1'b1) ? 32'd0 : tmp_3_3_3_reg_895_pp0_iter6_reg);

assign tmp_1_fu_332_p4 = {{bitcast_ln53_fu_329_p1[30:23]}};

assign tmp_4_fu_309_p4 = {{bitcast_ln53_1_fu_284_p1[30:23]}};

assign tmp_6_fu_381_p4 = {{bitcast_ln53_2_fu_378_p1[30:23]}};

assign tmp_7_fu_479_p4 = {{bitcast_ln53_4_fu_476_p1[30:23]}};

assign tmp_9_fu_430_p4 = {{bitcast_ln53_3_fu_427_p1[30:23]}};

assign trunc_ln53_1_fu_342_p1 = bitcast_ln53_fu_329_p1[22:0];

assign trunc_ln53_2_fu_391_p1 = bitcast_ln53_2_fu_378_p1[22:0];

assign trunc_ln53_3_fu_440_p1 = bitcast_ln53_3_fu_427_p1[22:0];

assign trunc_ln53_4_fu_489_p1 = bitcast_ln53_4_fu_476_p1[22:0];

assign trunc_ln53_fu_288_p1 = bitcast_ln53_1_fu_284_p1[22:0];

assign zext_ln51_1_fu_423_p1 = and_ln53_3_fu_418_p2;

assign zext_ln51_2_fu_472_p1 = and_ln53_5_fu_467_p2;

assign zext_ln51_fu_374_p1 = and_ln53_1_fu_369_p2;

assign zext_ln53_1_fu_538_p1 = add_ln53_reg_917;

assign zext_ln53_2_fu_541_p1 = add_ln53_1_reg_922;

assign zext_ln53_fu_522_p1 = and_ln53_7_fu_516_p2;

endmodule //myFuncAccel4
