#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("size", 32, hls_in, 0, "ap_stable", "in_data", 1),
	Port_Property("dim", 32, hls_in, 1, "ap_stable", "in_data", 1),
	Port_Property("threshold", 32, hls_in, 2, "ap_stable", "in_data", 1),
	Port_Property("data0_address0", 4, hls_out, 3, "ap_stable", "mem_address", 1),
	Port_Property("data0_ce0", 1, hls_out, 3, "ap_stable", "mem_ce", 1),
	Port_Property("data0_q0", 32, hls_in, 3, "ap_stable", "mem_dout", 1),
	Port_Property("data1_req_din", 1, hls_out, 4, "ap_bus", "fifo_data", 1),
	Port_Property("data1_req_full_n", 1, hls_in, 4, "ap_bus", "fifo_status", 1),
	Port_Property("data1_req_write", 1, hls_out, 4, "ap_bus", "fifo_update", 1),
	Port_Property("data1_rsp_empty_n", 1, hls_in, 4, "ap_bus", "fifo_status", 1),
	Port_Property("data1_rsp_read", 1, hls_out, 4, "ap_bus", "fifo_update", 1),
	Port_Property("data1_address", 32, hls_out, 4, "ap_bus", "unknown", 1),
	Port_Property("data1_datain", 32, hls_in, 4, "ap_bus", "unknown", 1),
	Port_Property("data1_dataout", 32, hls_out, 4, "ap_bus", "unknown", 1),
	Port_Property("data1_size", 32, hls_out, 4, "ap_bus", "unknown", 1),
	Port_Property("data2_req_din", 1, hls_out, 5, "ap_bus", "fifo_data", 1),
	Port_Property("data2_req_full_n", 1, hls_in, 5, "ap_bus", "fifo_status", 1),
	Port_Property("data2_req_write", 1, hls_out, 5, "ap_bus", "fifo_update", 1),
	Port_Property("data2_rsp_empty_n", 1, hls_in, 5, "ap_bus", "fifo_status", 1),
	Port_Property("data2_rsp_read", 1, hls_out, 5, "ap_bus", "fifo_update", 1),
	Port_Property("data2_address", 32, hls_out, 5, "ap_bus", "unknown", 1),
	Port_Property("data2_datain", 32, hls_in, 5, "ap_bus", "unknown", 1),
	Port_Property("data2_dataout", 32, hls_out, 5, "ap_bus", "unknown", 1),
	Port_Property("data2_size", 32, hls_out, 5, "ap_bus", "unknown", 1),
};
const char* HLS_Design_Meta::dut_name = "myFuncAccel";
