
log_wave -r /
set designtopgroup [add_wave_group "Design Top Signals"]
set coutputgroup [add_wave_group "C Outputs" -into $designtopgroup]
set data_out_group [add_wave_group data_out(axis) -into $coutputgroup]
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data_out_V_TREADY -into $data_out_group -color #ffff00 -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data_out_V_TVALID -into $data_out_group -color #ffff00 -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data_out_V_TDATA -into $data_out_group -radix hex
set cinputgroup [add_wave_group "C Inputs" -into $designtopgroup]
set data1_group [add_wave_group data1(axis) -into $cinputgroup]
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data1_V_TREADY -into $data1_group -color #ffff00 -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data1_V_TVALID -into $data1_group -color #ffff00 -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data1_V_TDATA -into $data1_group -radix hex
set data0_group [add_wave_group data0(wire) -into $cinputgroup]
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_255 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_254 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_253 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_252 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_251 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_250 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_249 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_248 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_247 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_246 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_245 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_244 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_243 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_242 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_241 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_240 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_239 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_238 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_237 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_236 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_235 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_234 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_233 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_232 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_231 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_230 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_229 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_228 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_227 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_226 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_225 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_224 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_223 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_222 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_221 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_220 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_219 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_218 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_217 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_216 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_215 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_214 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_213 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_212 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_211 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_210 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_209 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_208 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_207 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_206 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_205 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_204 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_203 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_202 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_201 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_200 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_199 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_198 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_197 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_196 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_195 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_194 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_193 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_192 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_191 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_190 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_189 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_188 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_187 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_186 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_185 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_184 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_183 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_182 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_181 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_180 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_179 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_178 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_177 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_176 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_175 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_174 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_173 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_172 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_171 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_170 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_169 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_168 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_167 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_166 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_165 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_164 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_163 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_162 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_161 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_160 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_159 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_158 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_157 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_156 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_155 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_154 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_153 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_152 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_151 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_150 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_149 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_148 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_147 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_146 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_145 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_144 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_143 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_142 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_141 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_140 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_139 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_138 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_137 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_136 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_135 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_134 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_133 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_132 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_131 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_130 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_129 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_128 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_127 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_126 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_125 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_124 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_123 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_122 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_121 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_120 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_119 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_118 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_117 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_116 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_115 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_114 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_113 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_112 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_111 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_110 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_109 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_108 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_107 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_106 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_105 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_104 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_103 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_102 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_101 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_100 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_99 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_98 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_97 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_96 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_95 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_94 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_93 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_92 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_91 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_90 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_89 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_88 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_87 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_86 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_85 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_84 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_83 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_82 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_81 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_80 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_79 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_78 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_77 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_76 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_75 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_74 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_73 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_72 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_71 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_70 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_69 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_68 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_67 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_66 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_65 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_64 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_63 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_62 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_61 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_60 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_59 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_58 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_57 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_56 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_55 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_54 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_53 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_52 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_51 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_50 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_49 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_48 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_47 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_46 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_45 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_44 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_43 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_42 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_41 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_40 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_39 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_38 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_37 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_36 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_35 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_34 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_33 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_32 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_31 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_30 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_29 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_28 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_27 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_26 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_25 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_24 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_23 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_22 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_21 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_20 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_19 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_18 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_17 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_16 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_15 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_14 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_13 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_12 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_11 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_10 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_9 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_8 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_7 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_6 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_5 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_4 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_3 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_2 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_1 -into $data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/data0_0 -into $data0_group -radix hex
set threshold_group [add_wave_group threshold(wire) -into $cinputgroup]
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/threshold -into $threshold_group -radix hex
set dim_group [add_wave_group dim(wire) -into $cinputgroup]
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/dim -into $dim_group -radix hex
set size_group [add_wave_group size(wire) -into $cinputgroup]
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/size -into $size_group -radix hex
set blocksiggroup [add_wave_group "Block-level IO Handshake" -into $designtopgroup]
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/ap_start -into $blocksiggroup
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/ap_done -into $blocksiggroup
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/ap_idle -into $blocksiggroup
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/ap_ready -into $blocksiggroup
set resetgroup [add_wave_group "Reset" -into $designtopgroup]
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/ap_rst_n -into $resetgroup
set clockgroup [add_wave_group "Clock" -into $designtopgroup]
add_wave /apatb_myFuncAccel16_top/AESL_inst_myFuncAccel16/ap_clk -into $clockgroup
set testbenchgroup [add_wave_group "Test Bench Signals"]
set tbinternalsiggroup [add_wave_group "Internal Signals" -into $testbenchgroup]
set tb_simstatus_group [add_wave_group "Simulation Status" -into $tbinternalsiggroup]
set tb_portdepth_group [add_wave_group "Port Depth" -into $tbinternalsiggroup]
add_wave /apatb_myFuncAccel16_top/AUTOTB_TRANSACTION_NUM -into $tb_simstatus_group -radix hex
add_wave /apatb_myFuncAccel16_top/ready_cnt -into $tb_simstatus_group -radix hex
add_wave /apatb_myFuncAccel16_top/done_cnt -into $tb_simstatus_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_size -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_threshold -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_0 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_1 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_2 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_3 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_4 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_5 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_6 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_7 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_8 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_9 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_10 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_11 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_12 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_13 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_14 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_15 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_16 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_17 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_18 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_19 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_20 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_21 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_22 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_23 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_24 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_25 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_26 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_27 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_28 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_29 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_30 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_31 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_32 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_33 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_34 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_35 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_36 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_37 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_38 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_39 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_40 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_41 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_42 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_43 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_44 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_45 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_46 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_47 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_48 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_49 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_50 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_51 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_52 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_53 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_54 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_55 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_56 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_57 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_58 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_59 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_60 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_61 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_62 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_63 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_64 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_65 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_66 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_67 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_68 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_69 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_70 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_71 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_72 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_73 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_74 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_75 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_76 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_77 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_78 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_79 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_80 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_81 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_82 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_83 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_84 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_85 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_86 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_87 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_88 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_89 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_90 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_91 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_92 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_93 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_94 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_95 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_96 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_97 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_98 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_99 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_100 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_101 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_102 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_103 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_104 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_105 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_106 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_107 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_108 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_109 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_110 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_111 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_112 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_113 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_114 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_115 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_116 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_117 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_118 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_119 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_120 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_121 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_122 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_123 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_124 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_125 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_126 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_127 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_128 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_129 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_130 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_131 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_132 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_133 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_134 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_135 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_136 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_137 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_138 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_139 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_140 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_141 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_142 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_143 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_144 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_145 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_146 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_147 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_148 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_149 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_150 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_151 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_152 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_153 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_154 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_155 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_156 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_157 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_158 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_159 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_160 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_161 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_162 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_163 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_164 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_165 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_166 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_167 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_168 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_169 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_170 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_171 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_172 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_173 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_174 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_175 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_176 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_177 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_178 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_179 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_180 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_181 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_182 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_183 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_184 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_185 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_186 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_187 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_188 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_189 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_190 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_191 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_192 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_193 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_194 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_195 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_196 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_197 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_198 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_199 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_200 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_201 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_202 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_203 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_204 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_205 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_206 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_207 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_208 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_209 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_210 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_211 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_212 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_213 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_214 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_215 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_216 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_217 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_218 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_219 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_220 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_221 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_222 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_223 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_224 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_225 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_226 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_227 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_228 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_229 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_230 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_231 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_232 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_233 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_234 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_235 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_236 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_237 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_238 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_239 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_240 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_241 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_242 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_243 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_244 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_245 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_246 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_247 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_248 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_249 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_250 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_251 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_252 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_253 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_254 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data0_255 -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data1_V -into $tb_portdepth_group -radix hex
add_wave /apatb_myFuncAccel16_top/LENGTH_data_out_V -into $tb_portdepth_group -radix hex
set tbcoutputgroup [add_wave_group "C Outputs" -into $testbenchgroup]
set tb_data_out_group [add_wave_group data_out(axis) -into $tbcoutputgroup]
add_wave /apatb_myFuncAccel16_top/data_out_V_TREADY -into $tb_data_out_group -color #ffff00 -radix hex
add_wave /apatb_myFuncAccel16_top/data_out_V_TVALID -into $tb_data_out_group -color #ffff00 -radix hex
add_wave /apatb_myFuncAccel16_top/data_out_V_TDATA -into $tb_data_out_group -radix hex
set tbcinputgroup [add_wave_group "C Inputs" -into $testbenchgroup]
set tb_data1_group [add_wave_group data1(axis) -into $tbcinputgroup]
add_wave /apatb_myFuncAccel16_top/data1_V_TREADY -into $tb_data1_group -color #ffff00 -radix hex
add_wave /apatb_myFuncAccel16_top/data1_V_TVALID -into $tb_data1_group -color #ffff00 -radix hex
add_wave /apatb_myFuncAccel16_top/data1_V_TDATA -into $tb_data1_group -radix hex
set tb_data0_group [add_wave_group data0(wire) -into $tbcinputgroup]
add_wave /apatb_myFuncAccel16_top/data0_255 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_254 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_253 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_252 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_251 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_250 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_249 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_248 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_247 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_246 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_245 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_244 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_243 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_242 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_241 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_240 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_239 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_238 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_237 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_236 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_235 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_234 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_233 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_232 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_231 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_230 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_229 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_228 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_227 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_226 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_225 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_224 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_223 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_222 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_221 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_220 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_219 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_218 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_217 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_216 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_215 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_214 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_213 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_212 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_211 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_210 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_209 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_208 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_207 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_206 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_205 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_204 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_203 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_202 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_201 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_200 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_199 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_198 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_197 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_196 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_195 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_194 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_193 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_192 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_191 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_190 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_189 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_188 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_187 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_186 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_185 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_184 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_183 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_182 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_181 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_180 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_179 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_178 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_177 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_176 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_175 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_174 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_173 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_172 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_171 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_170 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_169 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_168 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_167 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_166 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_165 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_164 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_163 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_162 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_161 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_160 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_159 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_158 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_157 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_156 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_155 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_154 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_153 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_152 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_151 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_150 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_149 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_148 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_147 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_146 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_145 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_144 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_143 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_142 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_141 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_140 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_139 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_138 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_137 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_136 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_135 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_134 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_133 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_132 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_131 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_130 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_129 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_128 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_127 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_126 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_125 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_124 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_123 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_122 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_121 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_120 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_119 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_118 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_117 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_116 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_115 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_114 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_113 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_112 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_111 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_110 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_109 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_108 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_107 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_106 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_105 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_104 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_103 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_102 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_101 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_100 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_99 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_98 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_97 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_96 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_95 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_94 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_93 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_92 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_91 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_90 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_89 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_88 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_87 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_86 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_85 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_84 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_83 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_82 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_81 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_80 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_79 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_78 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_77 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_76 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_75 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_74 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_73 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_72 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_71 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_70 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_69 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_68 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_67 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_66 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_65 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_64 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_63 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_62 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_61 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_60 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_59 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_58 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_57 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_56 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_55 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_54 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_53 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_52 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_51 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_50 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_49 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_48 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_47 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_46 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_45 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_44 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_43 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_42 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_41 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_40 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_39 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_38 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_37 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_36 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_35 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_34 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_33 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_32 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_31 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_30 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_29 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_28 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_27 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_26 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_25 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_24 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_23 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_22 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_21 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_20 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_19 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_18 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_17 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_16 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_15 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_14 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_13 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_12 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_11 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_10 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_9 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_8 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_7 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_6 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_5 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_4 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_3 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_2 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_1 -into $tb_data0_group -radix hex
add_wave /apatb_myFuncAccel16_top/data0_0 -into $tb_data0_group -radix hex
set tb_threshold_group [add_wave_group threshold(wire) -into $tbcinputgroup]
add_wave /apatb_myFuncAccel16_top/threshold -into $tb_threshold_group -radix hex
set tb_dim_group [add_wave_group dim(wire) -into $tbcinputgroup]
add_wave /apatb_myFuncAccel16_top/dim -into $tb_dim_group -radix hex
set tb_size_group [add_wave_group size(wire) -into $tbcinputgroup]
add_wave /apatb_myFuncAccel16_top/size -into $tb_size_group -radix hex
save_wave_config myFuncAccel16.wcfg
run all
quit

